/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wvKmxZPqiZb
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { JSX, SVGProps } from "react"

export function Todo() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md p-4 space-y-6 bg-white dark:bg-gray-800 rounded-md shadow-md">
        <h1 className="text-3xl font-bold text-center text-gray-900 dark:text-gray-100">To-Do List</h1>
        <form className="space-y-3">
          <Input className="w-full" id="new-task" placeholder="Add a new task" />
          <Button className="w-full" type="submit">
            Add Task
          </Button>
        </form>
        <ul className="space-y-3">
          <li className="flex items-center justify-between p-3 bg-gray-200 dark:bg-gray-700 rounded-md">
            <div className="flex items-center space-x-2">
              <Checkbox id="task-1" />
              <span className="text-gray-900 dark:text-gray-100">Task 1</span>
            </div>
            <Button size="icon" variant="ghost">
              <TrashIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            </Button>
          </li>
          <li className="flex items-center justify-between p-3 bg-gray-200 dark:bg-gray-700 rounded-md">
            <div className="flex items-center space-x-2">
              <Checkbox id="task-2" />
              <span className="text-gray-900 dark:text-gray-100">Task 2</span>
            </div>
            <Button size="icon" variant="ghost">
              <TrashIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            </Button>
          </li>
          <li className="flex items-center justify-between p-3 bg-gray-200 dark:bg-gray-700 rounded-md">
            <div className="flex items-center space-x-2">
              <Checkbox id="task-3" />
              <span className="text-gray-900 dark:text-gray-100">Task 3</span>
            </div>
            <Button size="icon" variant="ghost">
              <TrashIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            </Button>
          </li>
        </ul>
        <Button className="w-full" variant="outline">
          Clear Completed
        </Button>
      </div>
    </div>
  )
}


function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2v2" />
    </svg>
  )
}
